schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "8b9f39656aabfa59b1b8b8a80b83fd192de8a73e"
scrbench_pr_link = "https://github.com/piranna/linux-cmdline"
scrbench_commit_link = "https://github.com/piranna/linux-cmdline/commit/8b9f39656aabfa59b1b8b8a80b83fd192de8a73e"
scrbench_no_lines_changed = "67"
scrbench_no_lines_added = "36"
scrbench_no_lines_deleted = "31"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
