schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "13ad3b7170da6b78aae6e9464ebb2270e4da31da"
scrbench_pr_link = "https://github.com/lepture/mistune"
scrbench_commit_link = "https://github.com/lepture/mistune/commit/13ad3b7170da6b78aae6e9464ebb2270e4da31da"
scrbench_no_lines_changed = "21"
scrbench_no_lines_added = "13"
scrbench_no_lines_deleted = "8"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
