schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "8a31fac515a8883aa524f87cc5b60300d2dfb125"
scrbench_pr_link = "https://github.com/lepture/mistune"
scrbench_commit_link = "https://github.com/lepture/mistune/commit/8a31fac515a8883aa524f87cc5b60300d2dfb125"
scrbench_no_lines_changed = "10"
scrbench_no_lines_added = "8"
scrbench_no_lines_deleted = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
