schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "4caf1090abcc9868243d1ba9d002bc610e7450be"
scrbench_pr_link = "https://github.com/sequelize/sequelize"
scrbench_commit_link = "https://github.com/sequelize/sequelize/commit/4caf1090abcc9868243d1ba9d002bc610e7450be"
scrbench_no_lines_changed = "46"
scrbench_no_lines_added = "27"
scrbench_no_lines_deleted = "19"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
