schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "0ba5d1d4ad7fd6e442cc8bba5ea4735fcdf180b7"
scrbench_pr_link = "https://github.com/anymail/django-anymail"
scrbench_commit_link = "https://github.com/anymail/django-anymail/commit/0ba5d1d4ad7fd6e442cc8bba5ea4735fcdf180b7"
scrbench_no_lines_changed = "187"
scrbench_no_lines_added = "163"
scrbench_no_lines_deleted = "24"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
