schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "42be8f881bae69a3905aaf966fe32f5315aa840a"
scrbench_pr_link = "https://github.com/jonschlinkert/mixin-deep"
scrbench_commit_link = "https://github.com/jonschlinkert/mixin-deep/commit/42be8f881bae69a3905aaf966fe32f5315aa840a"
scrbench_no_lines_changed = "36"
scrbench_no_lines_added = "25"
scrbench_no_lines_deleted = "11"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
