schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "97c5a01ddc0af4d08e5fd5f84face665320e22c4"
scrbench_pr_link = "https://github.com/jonschlinkert/mixin-deep"
scrbench_commit_link = "https://github.com/jonschlinkert/mixin-deep/commit/97c5a01ddc0af4d08e5fd5f84face665320e22c4"
scrbench_no_lines_changed = "127"
scrbench_no_lines_added = "108"
scrbench_no_lines_deleted = "19"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
