schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "8d5d2c8230b9c232afd82e01039c680e8a8b0094"
scrbench_pr_link = "https://github.com/kanaka/noVNC"
scrbench_commit_link = "https://github.com/kanaka/noVNC/commit/8d5d2c8230b9c232afd82e01039c680e8a8b0094"
scrbench_no_lines_changed = "272"
scrbench_no_lines_added = "160"
scrbench_no_lines_deleted = "112"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
