schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "61d24f7dfa9abd845acd48fbb8a36f54a244e62e"
scrbench_pr_link = "https://github.com/simpleledger/slpjs"
scrbench_commit_link = "https://github.com/simpleledger/slpjs/commit/61d24f7dfa9abd845acd48fbb8a36f54a244e62e"
scrbench_no_lines_changed = "149"
scrbench_no_lines_added = "90"
scrbench_no_lines_deleted = "59"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
