schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "a1a1fb8ff25c80529b13b8a6b57419803153137d"
scrbench_pr_link = "https://github.com/mafintosh/tar-fs"
scrbench_commit_link = "https://github.com/mafintosh/tar-fs/commit/a1a1fb8ff25c80529b13b8a6b57419803153137d"
scrbench_no_lines_changed = "11"
scrbench_no_lines_added = "10"
scrbench_no_lines_deleted = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
