schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "a8dc5a6d760d00f78353c6943f30ea45756ecc9c"
scrbench_pr_link = "https://github.com/WeblateOrg/weblate"
scrbench_commit_link = "https://github.com/WeblateOrg/weblate/commit/a8dc5a6d760d00f78353c6943f30ea45756ecc9c"
scrbench_no_lines_changed = "21"
scrbench_no_lines_added = "15"
scrbench_no_lines_deleted = "6"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
