schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "90fc19934c62db5f2565d8d03b466b9c7d18eba2"
scrbench_pr_link = "https://github.com/substack/node-syntax-error"
scrbench_commit_link = "https://github.com/substack/node-syntax-error/commit/90fc19934c62db5f2565d8d03b466b9c7d18eba2"
scrbench_no_lines_changed = "59"
scrbench_no_lines_added = "59"
scrbench_no_lines_deleted = "0"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
