schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "ac36a99a7226e1092c2e7e28c9b6e32d8f82e6fb"
scrbench_pr_link = "https://github.com/ether/etherpad-lite"
scrbench_commit_link = "https://github.com/ether/etherpad-lite/commit/ac36a99a7226e1092c2e7e28c9b6e32d8f82e6fb"
scrbench_no_lines_changed = "143"
scrbench_no_lines_added = "101"
scrbench_no_lines_deleted = "42"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
