schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "bc05547cd8c1dd511c6b6a6c873a1bc63417b111"
scrbench_pr_link = "https://github.com/django/django"
scrbench_commit_link = "https://github.com/django/django/commit/bc05547cd8c1dd511c6b6a6c873a1bc63417b111"
scrbench_no_lines_changed = "81"
scrbench_no_lines_added = "58"
scrbench_no_lines_deleted = "23"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
