schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "937f8b80484d0677bfd58f3963b6419df33f84f0"
scrbench_pr_link = "https://github.com/certtools/intelmq-manager"
scrbench_commit_link = "https://github.com/certtools/intelmq-manager/commit/937f8b80484d0677bfd58f3963b6419df33f84f0"
scrbench_no_lines_changed = "115"
scrbench_no_lines_added = "55"
scrbench_no_lines_deleted = "60"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
