schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "bf5040f75e71e25af0b9b5c2a9c098c5933d4acc"
scrbench_pr_link = "https://github.com/Bcfg2/bcfg2"
scrbench_commit_link = "https://github.com/Bcfg2/bcfg2/commit/bf5040f75e71e25af0b9b5c2a9c098c5933d4acc"
scrbench_no_lines_changed = "13"
scrbench_no_lines_added = "10"
scrbench_no_lines_deleted = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
