schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "0877d424e08d57e6f0d1da9a86289fb10d0ee136"
scrbench_pr_link = "https://github.com/jquery/jquery"
scrbench_commit_link = "https://github.com/jquery/jquery/commit/0877d424e08d57e6f0d1da9a86289fb10d0ee136"
scrbench_no_lines_changed = "220"
scrbench_no_lines_added = "110"
scrbench_no_lines_deleted = "110"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
