schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "fca784f28a702f9795a482f2a6081db0a6b63032"
scrbench_pr_link = "https://github.com/totaljs/framework"
scrbench_commit_link = "https://github.com/totaljs/framework/commit/fca784f28a702f9795a482f2a6081db0a6b63032"
scrbench_no_lines_changed = "35"
scrbench_no_lines_added = "4"
scrbench_no_lines_deleted = "31"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
