schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "bbb3294c72e9f40c3447ce08c74a69494a12a7ce"
scrbench_pr_link = "https://github.com/rhysd/Shiba"
scrbench_commit_link = "https://github.com/rhysd/Shiba/commit/bbb3294c72e9f40c3447ce08c74a69494a12a7ce"
scrbench_no_lines_changed = "162"
scrbench_no_lines_added = "83"
scrbench_no_lines_deleted = "79"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
