schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "10f039b6fb4421324758d11666a4a5e352ce1d1c"
scrbench_pr_link = "https://github.com/Turistforeningen/node-im-metadata"
scrbench_commit_link = "https://github.com/Turistforeningen/node-im-metadata/commit/10f039b6fb4421324758d11666a4a5e352ce1d1c"
scrbench_no_lines_changed = "8"
scrbench_no_lines_added = "4"
scrbench_no_lines_deleted = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
