schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "7254cf0782dc768d4f54cfd5e2ff9ace6a8d6c2e"
scrbench_pr_link = "https://github.com/bottlepy/bottle"
scrbench_commit_link = "https://github.com/bottlepy/bottle/commit/7254cf0782dc768d4f54cfd5e2ff9ace6a8d6c2e"
scrbench_no_lines_changed = "64"
scrbench_no_lines_added = "32"
scrbench_no_lines_deleted = "32"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
