schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "eaccc87700760ed2d5a9aadae4d30fa9ab17453f"
scrbench_pr_link = "https://github.com/twangboy/salt"
scrbench_commit_link = "https://github.com/twangboy/salt/commit/eaccc87700760ed2d5a9aadae4d30fa9ab17453f"
scrbench_no_lines_changed = "166"
scrbench_no_lines_added = "154"
scrbench_no_lines_deleted = "12"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
