schema_version = "1.0"
source = "SCRBench"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
scrbench_id = "91bc67d81a9711fbf5a0f0c46bbf1d87232391f8"
scrbench_pr_link = "https://github.com/openstack/nova"
scrbench_commit_link = "https://github.com/openstack/nova/commit/91bc67d81a9711fbf5a0f0c46bbf1d87232391f8"
scrbench_no_lines_changed = "199"
scrbench_no_lines_added = "198"
scrbench_no_lines_deleted = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
